import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { textFont } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={textFont.className}>
        <Header />
        <main
          className={`min-w-wh min-h-[80vh] flex flex-col justify-start items-center pt-16 md:pt-[8%] font-extrabold`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
